[package]
name = "rust-witness"
version = "0.1.0"
edition = "2021"

[dependencies]
fnv = "1.0.7"
num-bigint = "0.4.5"
num-traits = "0.2.19"
paste = "1.0.15"
quote = "1.0.36"

[build-dependencies]
cc = "1.0"
