[package]
name = "rust-witness"
version = "0.1.0"
edition = "2021"

[dependencies]
cc = "1.0"
fnv = "1.0.7"
num-bigint = "0.4.0"
num-traits = "0.2.0"
paste = "1.0.0"
walkdir = "2.5.0"

[build-dependencies]
cc = "1.0"
walkdir = "2.5.0"

[lib]
