name: Build and Test

on:
    push:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review

env:
    CARGO_TERM_COLOR: always
    SCCACHE_GHA_ENABLED: "false"
    RUSTC_WRAPPER: "sccache"

jobs:
    # TODO: Add a job to run clippy
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Check formatting
              run: cargo fmt --all -- --check
            - name: Check template formating
              run: cargo fmt --all -- --check

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Submodules
              run: git submodules init && git submodule update
            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: "1.77"
                  override: true
            - name: Run sccache-cache
              uses: mozilla-actions/sccache-action@v0.0.3
            - name: Cache gmp
              uses: actions/cache/restore@v4
              with:
                key: gmp
                path: |
                    depends/gmp-6.2.1.tar.xz
            - name: Build gmp
              run: ./build_gmp.sh host
            - name: Cache gmp
              uses: actions/cache/save@v4
              with:
                key: gmp
                path: |
                    depends/gmp-6.2.1.tar.xz
            - name: Build witness CPP
              run: cd circom && make
            - name: Build rust
              run: cargo build
            - name: Generate witness
              run: cargo run